<?php
$language= array(
	"th"=>array(
		"home"=>'หน้าแรกเว็บไซต์',
	  "sitename"=>'BUU CHAN News',
		"meta_title"=>'Burapha University Chanthaburi Campus',
		"meta_description"=>'ม.บูรพา,มอบู,ม.บูร,มหาวิทยาลัยบูรพา วิทยาเขตจันทบุรี, มหาวิทยาลัยบูรพา, วิทยาเขตจันทบุรี',
		"address"=>'เลขที่ ๕๗ หมู่ ๑ ถนนชลประทาน <span>ตำบลโขมง อำเภอท่าใหม่ จังหวัดจันทบุรี </span>',
		"copyright"=>'Burapha University Chanthaburi Campus.',
		"allrights"=>'All rights reserved. Comments to webmaster : ',
		"title"=>array(
			"change_status"=>'เปลี่ยนสถานะ',
			"edit_ranking"=>'แก้ไขลำดับ',
			"edit"=>'แก้ไขข้อมูล',
			"reset_password"=>'รีเซ็ตรหัสผ่าน',
			"detail"=>'ดูรายละเอียด',
		),
		"action"=>array(
			"add"=>'เพิ่มข้อมูล',
			"edit"=>'แก้ไข',
			"btn_copy"=>'คัดลอก',
			"delete_selected"=>'ลบรายการที่เลือก',
			"menu"=>'ตัวจัดการ',
			"manage"=>'จัดการ',
			"reset_filter"=>'รีเซ็ตตัวกรอง',
			"reseted"=>'รีเซ็ต',
			"search"=>'ค้นหา',
			"upload"=>'อัพโหลด',
		),
		"label"=>array(
			"attachment"=>'เอกสารแนบ',
			"adjust_image"=>'ปรับภาพให้พอดี',
			"breadcrumbs"=>'Breadcrumbs',
			"banner_img"=>'ภาพแบนเนอร์',
			"banner_mb_img"=>'ภาพแบนเนอร์(มือถือ)',
			"confirm_password"=>'ยืนยันรหัสผ่านใหม่',
			"copyright"=>'Copyright',
			"description"=>'รายละเอียด',
			"delete"=>'ลบ',
			"department"=>'หน่วยงาน',
			"date_start"=>'วันเวลาเริ่มแสดง',
			"date_end"=>'วันเวลาสิ้นสุด',
			"email"=>'อีเมล์',
			"ex_photo"=>'ภาพตัวอย่าง',
			"from"=>'จาก',
			"files"=>'ไฟล์',
			"featured"=>'ข่าวเด่น',
			"gallery"=>'แกลอรี่(ใบบอกข่าว)',
			"hello"=>'สวัสดี',
			"id"=>'รหัส',
			"images"=>'รูปภาพ',
			"link_url"=>'ลิงค์',
			"link_youtube"=>'ลิงค์ Youtube',
			"level"=>'ระดับสิทธิ์',
			"overview"=>'หัวข้อข่าว (ถ้ายาว)',
			"page"=>'หน้า',
			"phone"=>'โทรศัพท์',
			"password"=>'รหัสผ่าน',
			"performer"=>'โดย',
			"read_more"=>'อ่านรายละเอียด',
			"reset_password"=>'รีเซ็ตรหัสผ่าน',
			"ranking"=>'เรียงลำดับ',
			"rotate_cw"=>'หมุนตามเข็มนาฬิกา',
			"rotate_ccw"=>'หมุนทวนเข็มนาฬิกา',
			"nbcount"=>'ครั้ง',
			"name"=>'ชื่อ',
			"new_password"=>'รหัสผ่านใหม่',
			"news_title"=>'หัวข้อข่าว',
			"news_category"=>'ประเภทข่าว',
			"news_thumbnail"=>'รูปภาพข่าว',
			"slidecode"=>'สไลด์แกลอรี่',
			"status"=>'สถานะ',
			"sort_order"=>'เรียงลำดับ',
			"select"=>'เลือก',
			"sticky"=>'ปักหมุด',
			"select_photo"=>'เลือกรูปภาพ',
			"type"=>'ประเภท',
			"title"=>'หัวข้อ',
			"welcome"=>'ยินดีต้อนรับ',
			"username"=>'ชื่อผู้ใช้',
			"upload"=>'อัพโหลด',
			"upload_img"=>'อัพโหลดรูปภาพ',
			"upload_files"=>'อัพโหลดไฟล์',
			"visit"=>'เข้าชม',
		),
		"page"=>array(
			"home"=>'หน้าแรก',
			"attachment"=>'เอกสารแนบ',
			"department_add"=>'เพิ่มหน่วยงาน',
			"department_edit"=>'แก้ไขหน่วยงาน',
			"newstype_add"=>'เพิ่มประเภทข่าว',
			"newstype_edit"=>'แก้ไขประเภทข่าว',
		  "edit_ranking"=>'แก้ไขลำดับ',
			"setPassword"=>'รีเซ็ตรหัสผ่าน',
			"slide_add"=>'เพิ่มภาพสไลด์',
			"slide_view"=>'ข้อมูลภาพสไลด์',
			"slide_edit"=>'แก้ไขข้อมูลภาพสไลด์',
			"news_add"=>'เพิ่มข่าว/กิจกรรม',
			"news_manage"=>'จัดการข่าว/กิจกรรม',
			"news_thumbnail"=>'รูปภาพข่าว',
			"news_gallery"=>'แกลอรี่(ใบบอกข่าว)',
			"news_manage_gallery"=>'จัดการแกลอรี่',
			"news_manage_attachment"=>'จัดการเอกสารแนบ',
			"news_images"=>'รูปภาพข่าว/กิจกรรม',
			"news_images_data"=>'ข้อมูลรูปภาพ',
			"news_view"=>'ข้อมูลข่าว/กิจกรรม',
			"user_login"=>'ผู้ดูแลระบบ',
		),
		"front"=>array(
			"home"=>'หน้าแรก',
			"news"=>'ข่าว',
			"newslist"=>'ข่าวสาร',
			"department"=>'หน่วยงาน',
			"newtype"=>'ประเภทข่าว',
			"title"=>array(
				"today"=>'วันนี้',
				"lasted"=>'ล่าสุด',
				"included_lasted"=>'รวมล่าสุด',
				"sticky"=>'ข่าวปักหมุด',
				"featured"=>'ข่าวเด่น',
				"included"=>'ข่าวรวม',
				"activity"=>'ภาพกิจกรรม',
			),
		),
		"menu"=>array(
				"dashboard"=>'หน้าหลัก',
				"moderator"=>array(
					"main"=>'สำหรับผู้ดูแล',
					"department"=>'หน่วยงาน',
					"newstype"=>'ประเภทข่าว',
					"account"=>'บัญชีผู้ใช้',
					"slide"=>'ภาพสไลด์',
					"setting"=>'ตั้งค่าเว็บไซต์',
					"news"=>'ข่าว/กิจกรรม',
					"images"=>'ภาพข่าว/กิจกรรม',
				),
				"account"=>'บัญชีผู้ใช้',
				"slide"=>'ภาพสไลด์',
				"news"=>'ข่าว/กิจกรรม',
		),
		"module"=>array(
			"user"=>array(
				"login"=>'ล็อกอินเข้าใช้งาน',
				"setPassword"=>'รีเซ็ตรหัสผ่าน',
			),
			"account"=>array(
				"list"=>'รายการบัญชีผู้ใช้',
				"profiles"=>'โปรไฟล์',
				"logout"=>'ออกจากระบบ',
			),
			"slide"=>array(
				"list"=>'รายการภาพสไลด์',
			),
			"news"=>array(
				"list"=>'รายการข่าว/กิจกรรม',
				"images"=>'ภาพข่าว/กิจกรรม',
			),
		),
		"alert"=>array(
			  "confirm"=>array(
					  "change_status"=>'คุณต้องการเปลี่ยนแปลงสถานะของรายการรหัส',
						"logout"=>'คุณต้องการออกจากระบบ',
						"reset_password"=>'คุณต้องการรีเซ็ตรหัสผ่านของรายการรหัส',
						"delete_all"=>'คุณต้องการลบรายการที่มีรหัสดังนี้:',
						"images_delete"=>'คุณต้องการลบรูปภาพรหัส:',
						"reserve_images_delete"=>'คุณต้องการลบรูปภาพข่าว',
		    ),
				"save"=>array(
						"success"=>'บันทึกสำเร็จ',
            "fail"=>'บันทึกไม่สำเร็จ!',
						"news_thumbnail_fail"=>'บันทึกรูปภาพข่าวไม่สำเร็จ!',
				),
				"duplicate"=>array(
						"name"=>'ชื่อซ้ำกับที่มีในระบบ!',
				),
				"delete"=>array(
						"success"=>'ลบข้อมูลสำเร็จ',
            "fail"=>'ลบข้อมูลไม่สำเร็จ!',
				),
				"success"=>array(
					  "proceed"=>'ดำเนินการสำเร็จ',
					  "resetPassword"=>'รีเซ็ตรหัสผ่านสำเร็จ',
						"copylink"=>'คัดลอกลิงค์สำเร็จ',
						"copied"=>'คัดลอกสำเร็จ',
				),
				"fail"=>array(
					  "proceed"=>'พบข้อผิดพลาด!',
						"resetPassword"=>'ไม่สามารถรีเซ็ตรหัสผ่านได้ โปรดติดต่อผู้ดูแล',
				),
				"incorrect"=>array(
							"email"=>'รูปแบบอีเมล์ไม่ถูกต้อง!',
							"link_url"=>'ลิงค์ไม่ถูกต้อง!',
							"login_fail"=>'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง!',
						  "img_extension_limit"=>'เฉพาะนามสกุลไฟล์ *.png, *.jpg, *.jpeg, และ *.gif เท่านั้น!',
							"files_extensions_limit"=>'เฉพาะนามสกุลไฟล์ *.pdf, *.doc, *.docx,*.xls, และ *.xlsx เท่านั้น!',
						  "files_size_limit"=>'ไม่สามารถอัพโหลดไฟล์ที่มีขนาดเกิน 5 MB!',
				),
				"loading"=>array(
							"please_wait"=>'โปรดรอสักครู่',
				),
				"required"=>array(
							"description"=>'โปรดกรอกข้อมูลรายละเอียด!',
				),
				"token"=>array(
					"expired"=>'โทเค็นหมดอายุ!',
				),
				"notfound"=>array(
							"id"=>'ไม่พบรายการรหัส: ',
							"data"=>'ยังไม่มีข้อมูล',
				),
				"notify"=>array(
					    "check_news_thumbnail"=>'รูปภาพต้องมีขนาดไม่น้อยกว่า 740x493px!',
					    "limit_select_images"=>'กรุณาอัพโหลดรูปภาพครั้งละไม่เกิน 20 รูป!',
							"limit_select_files"=>'กรุณาอัพโหลดไฟล์ครั้งละไม่เกิน 20 ไฟล์!',
							"reset_password"=>'อยู่รหว่างดำเนินการ',
							"pw_least8"=>'รหัสผ่านอย่างน้อย 4 ตัวอักษร',
							"password_success"=>'รีเซ็ตรหัสผ่านสำเร็จ',
						  "status_success"=>'เปลี่ยนแปลงสถานะสำเร็จ',
						  "fail"=>'ดำเนินการไม่สำเร็จ!',
							"none_select"=>'คุณยังไม่ได้เลือกรายการ!',
							"error"=>'ไม่พบข้อมูล!',
				),
				"upload"=>array(
							"success"=>'อัพโหลดสำเร็จ',
							"fail"=>'ไม่สามารถอัพโหลดได้!',
				),
		),
		"dataTables" => array(
					"zeroRecords"=>'ไม่พบข้อมูล',
					"lengthMenu"=>'แสดง _MENU_ รายการ',
					"info"=>'แสดง _START_ ถึง _END_ จาก _TOTAL_ รายการ',
					"sInfoEmpty"=>'แสดง 0 ถึง 0 จาก 0 รายการ',
					"sInfoFiltered"=>'(กรองข้อมูล _MAX_ ทุกรายการ)',
					"emptyTable"=>'ไม่มีข้อมูลในตาราง',
					"search"=>'ค้นหา: ',
					"paginate_first"=>'หน้าแรก',
					"paginate_next"=>'ถัดไป',
					"paginate_previous"=>'ก่อนหน้า',
					"paginate_last"=>'หน้าสุดท้าย',
					"select_more"=>'เลือกทั้งหมด %d รายการ',
					"confirm_reset"=>'คุณต้องการรีเซ็ตตัวกรอง',
					"reset_ok"=>'รีเซ็ตตัวกรองสำเร็จ',
		),
		"status" => array(
					"enabled"=>'เปิด',
					"disable"=>'ปิด',
		),
		"level" => array(
					"member"=>'สมาชิก',
					"admin"=>'ผู้ดูแล',
		),
		"button" => array(
			    "edit"=>'แก้ไข',
			    "back"=>'ย้อนกลับ',
					"delete"=>'ลบ',
					"confirm"=>'ยืนยัน',
					"cancel"=>'ยกเลิก',
					"close"=>'ปิด',
					"login"=>'เข้าสู่ระบบ',
					"save"=>'บันทึก',
					"share"=>'แชร์',
					"ok"=>'ตกลง',
		),
		"placeholder" => array(
			    "breadcrumbs"=>'ขนาดไฟล์ 2000x500px และไฟล์ *.png, *.jpg, *.jpeg, และ *.gif เท่านั้น!',
			    "news_thumbnail"=>'ขนาดไม่น้อยกว่า 740x493px และไฟล์ *.png, *.jpg, *.jpeg, และ *.gif เท่านั้น!',
					"news_gallery"=>'ขนาดไม่น้อยกว่า 740x493px และไฟล์ *.png, *.jpg, *.jpeg, และ *.gif เท่านั้น!',
					"slide_banner"=>'ขนาดความกว้างไม่เกิน 1900px และไฟล์ *.png, *.jpg, *.jpeg, และ *.gif เท่านั้น!',
					"slide_mbbanner"=>'ขนาดความกว้างไม่เกิน 768px และไฟล์ *.png, *.jpg, *.jpeg, และ *.gif เท่านั้น!',
			    "images_extensions"=>'ไฟล์ *.png, *.jpg, *.jpeg, และ *.gif เท่านั้น!',
					"files_extensions"=>'ไฟล์ *.pdf, *.doc, *.docx,*.xls, และ *.xlsx เท่านั้น!',
			    "maxwidth_1170"=>'ขนาดความกว้างไม่เกิน 1170px',
					"maxwidth_768"=>'ขนาดความกว้างไม่เกิน 768px',
					"link_url"=>'ตัวอย่าง : http://www.website.com',
					"sort_desc"=>'เรียงลำดับจากมากไปน้อย',
					"search_news"=>'ค้นหาข่าว',
					"search_date"=>'เลือกวันที่ต้องการค้นหา',
					"search_title"=>'ค้นหาจากหัวข้อข่าว',
					"multi_select"=>'กดปุ่ม Ctrl หรือ Shift เพื่อเลือกมากกว่า 1 รายการ',
		),
	)
);
?>
