<?php
$setURI= array(
	"home"=>FRONT_URL,
	"dashboard"=>BACK_URL.'?select=dashboard',
	"backend"=>array(
    "module"=>array(
		  "moderator"=>array(
			  "department"=>BACK_URL.'?select=moderator&tab=department',
			  "newstype"=>BACK_URL.'?select=moderator&tab=newstype',
			  "news"=>BACK_URL.'?select=moderator&tab=news',
			  "images"=>BACK_URL.'?select=moderator&tab=images',
				"setting"=>BACK_URL.'?select=moderator&tab=setting',
				"report"=>BACK_URL.'?select=moderator&tab=report',
				"log"=>BACK_URL.'?select=moderator&tab=log',
      ),
			"print"=>array(
				"report"=>BACK_URL.'?select=print&tab=report',
      ),
      "account"=>array(
			  "list"=>BACK_URL.'?select=account&tab=list',
      ),
		  "user"=>array(
			  "login"=>BACK_URL.'?select=user&service=login',
			  "logout"=>BACK_URL.'?select=user&service=logout',
			  "setPassword"=>BACK_URL.'?select=user&service=setPassword&uid=',
			  "form"=>BACK_URL.'?select=Authorization',
      ),
		  "slide"=>array(
			  "list"=>BACK_URL.'?select=slide&tab=list',
			  "add"=>BACK_URL.'?select=slide&tab=add',
			  "edit"=>BACK_URL.'?select=slide&tab=edit&id=',
			  "view"=>BACK_URL.'?select=slide&tab=view&id=',
      ),
		  "news"=>array(
			  "add"=>BACK_URL.'?select=news&tab=add',
        "list"=>BACK_URL.'?select=news&tab=list',
			  "manage"=>BACK_URL.'?select=news&tab=manage&id=',
			  "view"=>BACK_URL.'?select=news&tab=view&id=',
			  "images"=>BACK_URL.'?select=news&tab=images',
      ),
    ),
	  "process"=>BACK_URL.'?select=Process',
	  "loading"=>BACK_URL.'?select=Loading',
	),
	"front"=>array(
		"module"=>array(
			"news"=>array(
				"detail"=>FRONT_URL.'?select=news&m=detail&id=',
				"list"=>FRONT_URL.'?select=news',
				"department"=>FRONT_URL.'?select=news&d=',
				"category"=>FRONT_URL.'?select=news&c=',
			),
			"search"=>array(
				"list"=>FRONT_URL.'?select=search',
			),
		),
	),
);
?>
